In [48]:
import pandas as pd
import requests
from io import StringIO
from google.colab import files

In [24]:
url = "https://www.howstat.com/Cricket/Statistics/Series/SeriesAnalysis.asp?SeriesCode=0863&Scope=All"

In [30]:
response = requests.get(url)
html_read = StringIO(response.text)
table  = pd.read_html(html_read)

In [35]:
df = table[3]

In [43]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Player,Country,Mat,Inns,NO,50s,100s,0s,HS,Runs,S/R,Avg,Ca,St,% Team Runs
1,"Jadeja, R A",India,5,10,4,5,1,0,107*,516,55.07,86.00,1,0,13.55%
2,Shubman Gill,India,5,10,0,0,4,0,269,754,65.57,75.40,3,0,19.80%
3,"Pant, R R",India,4,7,0,3,2,0,134,479,77.63,68.43,7,0,12.58%
4,"Root, J E",England,5,9,1,1,3,0,150,537,56.89,67.13,5,0,15.90%
5,"Smith, J L",England,5,9,2,2,1,0,184*,434,79.78,62.00,20,1,12.85%
6,"Brook, H C",England,5,9,0,2,2,1,158,481,81.39,53.44,11,0,14.24%
7,"Rahul, K L",India,5,10,0,2,2,0,137,532,49.91,53.20,6,0,13.97%
8,"Duckett, B M",England,5,9,0,3,1,1,149,462,82.94,51.33,3,0,13.68%
9,Washington Sundar,India,4,8,2,1,1,1,101*,284,48.38,47.33,1,0,7.46%
10,"Stokes, B A",England,4,7,0,0,1,1,141,304,52.32,43.43,0,0,9.00%
11,"Jaiswal, Y B K",India,5,10,0,2,2,2,118,411,68.73,41.10,1,0,10.79%
12,"Pope, O J D",England,5,9,0,1,1,1,106,306,58.51,34.00,2,0,9.06%
13,"Crawley, Z",England,5,9,0,3,0,1,84,290,62.10,32.22,6,0,8.58%
14,"Carse, B A",England,4,6,0,1,0,1,56,164,75.93,27.33,1,0,4.85%
15,"Jurel, D C",India,1,2,0,0,0,0,34,53,61.63,26.50,3,0,1.39%
16,"Dawson, L A",England,1,1,0,0,0,0,26,26,40.00,26.00,0,0,0.77%
17,"Nair, K K",India,4,8,0,1,0,1,57,205,52.56,25.63,4,0,5.38%
18,"Sai Sudharsan, B S",India,3,6,0,1,0,2,61,140,41.06,23.33,2,0,3.68%
19,"Akash Deep, A",India,3,5,1,1,0,0,66,80,59.26,20.00,1,0,2.10%
20,"Thakur, S N",India,2,3,0,0,0,0,41,46,42.59,15.33,1,0,1.21%
21,"Atkinson, A A P",England,1,2,0,0,0,0,17,28,62.22,14.00,1,0,0.83%
22,"Reddy, N K",India,2,4,0,0,0,0,30,45,29.61,11.25,0,0,1.18%
23,"Archer, J C",England,2,3,2,0,0,0,5*,11,28.21,11.00,1,0,0.33%
24,"Woakes, C R",England,5,7,1,0,0,1,38,64,41.29,10.67,2,0,1.89%
25,Shoaib Bashir,England,3,5,3,0,0,1,12*,16,43.24,8.00,1,0,0.47%
26,"Bethell, J G",England,1,2,0,0,0,0,6,11,24.44,5.50,0,0,0.33%
27,"Overton, J",England,1,2,0,0,0,1,9,9,42.86,4.50,2,0,0.27%
28,Mohammed Siraj,India,5,8,3,0,0,3,8,20,25.97,4.00,4,0,0.53%
29,"Tongue, J C",England,3,5,1,0,0,2,11,13,19.12,3.25,2,0,0.38%
30,"Prasidh Krishna, M",India,3,5,2,0,0,2,5*,6,15.79,2.00,0,0,0.16%
31,"Bumrah, J J",India,3,5,0,0,0,3,5,9,11.84,1.80,1,0,0.24%
32,"Anshul Kamboj, A",India,1,1,0,0,0,1,0,0,0.00,0.00,0,0,NaN

In [45]:
df = df.iloc[:, :-3]
df

                     0        1    2     3   4    5     6   7     8
0               Player  Country  Mat  Inns  NO  50s  100s  0s    HS
1          Jadeja, R A    India    5    10   4    5     1   0  107*
2         Shubman Gill    India    5    10   0    0     4   0   269
3            Pant, R R    India    4     7   0    3     2   0   134
4            Root, J E  England    5     9   1    1     3   0   150
5           Smith, J L  England    5     9   2    2     1   0  184*
6           Brook, H C  England    5     9   0    2     2   1   158
7           Rahul, K L    India    5    10   0    2     2   0   137
8         Duckett, B M  England    5     9   0    3     1   1   149
9    Washington Sundar    India    4     8   2    1     1   1  101*
10         Stokes, B A  England    4     7   0    0     1   1   141
11      Jaiswal, Y B K    India    5    10   0    2     2   2   118
12         Pope, O J D  England    5     9   0    1     1   1   106
13          Crawley, Z  England    5     9   0    3     0   1    84
14          Carse, B A  England    4     6   0    1     0   1    56
15          Jurel, D C    India    1     2   0    0     0   0    34
16         Dawson, L A  England    1     1   0    0     0   0    26
17           Nair, K K    India    4     8   0    1     0   1    57
18  Sai Sudharsan, B S    India    3     6   0    1     0   2    61
19       Akash Deep, A    India    3     5   1    1     0   0    66
20         Thakur, S N    India    2     3   0    0     0   0    41
21     Atkinson, A A P  England    1     2   0    0     0   0    17
22          Reddy, N K    India    2     4   0    0     0   0    30
23         Archer, J C  England    2     3   2    0     0   0    5*
24         Woakes, C R  England    5     7   1    0     0   1    38
25       Shoaib Bashir  England    3     5   3    0     0   1   12*
26        Bethell, J G  England    1     2   0    0     0   0     6
27          Overton, J  England    1     2   0    0     0   1     9
28      Mohammed Siraj    India    5     8   3    0     0   3     8
29         Tongue, J C  England    3     5   1    0     0   2    11
30  Prasidh Krishna, M    India    3     5   2    0     0   2    5*
31         Bumrah, J J    India    3     5   0    0     0   3     5
32    Anshul Kamboj, A    India    1     1   0    0     0   1     0

In [49]:
df.to_csv("battingstats.csv",index= "False")
files.download("battingstats.csv")